# Generated by Django 3.2.18 on 2023-03-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('numeroHabitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoHabitacion', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField(auto_now=True)),
                ('fechaLlegada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('estado', models.CharField(max_length=25)),
                ('origen', models.CharField(max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detalleReserva',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('codigoHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.habitacion')),
                ('codigoReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.reserva')),
            ],
        ),
    ]
